### ISSUE TITLE
HiveOS not showing proper CPU temperatures

### ISSUE THREAD

**Issue by kio3i0j9024vkoenio** [minershive/hiveos-linux#1]
System is an HP DL 580 G7. HiveOS shows 8.3 degrees for all processor cores. This is a bug in HiveOS.

Installing and running lm-sensors shows the correct processor core temperatures ranging from 59 to 75 degrees.

HiveOS is picking this wrong sensor for all the processor cores:

acpitz-virtual-0
Adapter: Virtual device
temp1: +8.3°C (crit = +31.3°C)

That is the BUG. It should be using these sensors:

coretemp-isa-0002
Adapter: ISA adapter
Core 0: +59.0°C (high = +79.0°C, crit = +95.0°C)
Core 1: +55.0°C (high = +79.0°C, crit = +95.0°C)
Core 2: +59.0°C (high = +79.0°C, crit = +95.0°C)
Core 8: +63.0°C (high = +79.0°C, crit = +95.0°C)
Core 17: +61.0°C (high = +79.0°C, crit = +95.0°C)
Core 18: +62.0°C (high = +79.0°C, crit = +95.0°C)
Core 24: +64.0°C (high = +79.0°C, crit = +95.0°C)
Core 25: +59.0°C (high = +79.0°C, crit = +95.0°C)

coretemp-isa-0000
Adapter: ISA adapter

coretemp-isa-0003
Adapter: ISA adapter

coretemp-isa-0001
Adapter: ISA adapter

Please fix

**Comment by minershive** [comment]
agent relies on thermal_zone files
`cat /sys/class/thermal/thermal_zone*/temp`
could you please what you have on your system in that files?

**Comment by kio3i0j9024vkoenio** [comment]
Result is a single value: 8300

I guess that is where the 8.3°C comes from. However that is wrong as my DL580 has 4x E7-8838's with 8 cores in each. HiveOS picks this sensor "acpitz-virtual-0 Adapter: Virtual device temp1: +8.3°C (crit = +31.3°C)" and them posts the 8.3°C to all 32 cores which is wrong.

lm-sensors shows the correct sensors to use for each processor (coretemp-isa-0000, coretemp-isa-0001, coretemp-isa-0002, coretemp-isa-0003) Adapter: ISA adapter and the current temperatures for each of the 8 cores in each processor.

**Comment by minershive** [comment]
you have only 1 file in  /sys/class/thermal* ?
in order to help we need to find proper files in /sys/class/thermal*
hive knows nothing about acpitz-virtual-0

**Comment by kio3i0j9024vkoenio** [comment]
Well it's not like I put it there. It is what HiveOS did.

I just installed HiveOS on my 3rd HP DL580 G7 Rig and booted up HiveOS for the first time on it. I entered Rig ID and password. It updated itself to Version 0.5-42. It is currently mining fine but it too has the 8.3°C for all the processor cores.

On this fresh untouched HiveOS install I opened a Shellinabox to it and did the "cat /sys/class/thermal/thermal_zone*/temp" command.

The result is exactly the same: one file named 8300.

**Comment by minershive** [comment]
Can't help you without knowing your system (without access).
If you can point in which sys file have correct temps - we could fix that.

**Comment by kio3i0j9024vkoenio** [comment]
The latest version of HiveOS 0.5-47 for Linux is still not correctly showing the core temperatures. It is still showing +8.3°C. I had hope that the change to the Linux 4.13 kernel would fix this issue.

Why not have HiveOS install lm-sensors and then get the correct core temperatures from it?

----

I simply did this in Shellinabox to get lm-sensors installed: apt install lm-sensors
Then typed: sensors

Which then showed the correct core temperatures:

coretemp-isa-0001
Adapter: ISA adapter
Core 0:       +60.0°C  (high = +79.0°C, crit = +95.0°C)
Core 1:       +65.0°C  (high = +79.0°C, crit = +95.0°C)
Core 2:       +65.0°C  (high = +79.0°C, crit = +95.0°C)
...

Doesn't lm-sensors have an API that HiveOS could get the correct core temperatures from.

**Comment by minershive** [comment]
added k10temp module in 0.5-51
