### ISSUE TITLE
Cortex - Herominers : URL typo issue

### ISSUE THREAD

**Issue by luizrrodrigues** [minershive/hiveos-linux#106]
Check herominers URLs to Cortex (CTXC), have typo, missing `c`:

![image](https://user-images.githubusercontent.com/7029641/109742331-9daf4480-7bad-11eb-8cb4-239c034a8cce.png)

**Comment by HaloGenius** [comment]
Related to https://github.com/minershive/hive-pooltemplates
Herominers templates mantained by pool owner

anyway thanks (fixed)
