### ISSUE TITLE
Does not show CPU Temp on old motherboard

### ISSUE THREAD

**Issue by ezshua** [minershive/hiveos-linux#108]
Hello 

Motherboard P5LD2-SE ASUSTeK Computer INC. (1301 08/16/2007)
CPU 2 × Intel(R) Pentium(R) Dual CPU E2140 @ 1.60GHz
Kernel 5.4.80-hiveos
OS VERSION 0.6-203@210403 (today upgraded from hiveos-0.6-190-stable@210108)
CPU TEMP 0°

Temperature from CPU always zero degrees after update!
Temperarure from GPU show without problem!

sensors output:
atk0110-acpi-0
Adapter: ACPI interface
Vcore Voltage:      +1.24 V  (min =  +0.85 V, max =  +1.60 V)
 +3.3 Voltage:      +3.33 V  (min =  +2.97 V, max =  +3.63 V)
 +5 Voltage:        +5.02 V  (min =  +4.50 V, max =  +5.50 V)
 +12 Voltage:      +11.98 V  (min = +10.20 V, max = +13.80 V)
CPU FAN Speed:     2057 RPM  (min =  600 RPM, max = 7200 RPM)
CHASSIS FAN Speed:    0 RPM  (min =  800 RPM, max = 7200 RPM)
POWER FAN Speed:      0 RPM  (min =  800 RPM, max = 7200 RPM)
CPU Temperature:    +47.0°C  (high = +60.0°C, crit = +95.0°C)
MB Temperature:     +36.0°C  (high = +45.0°C, crit = +95.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +52.0°C  (high = +86.0°C, crit = +100.0°C)
Core 1:       +52.0°C  (high = +86.0°C, crit = +100.0°C)

What I can do with it or how fix it?

**Comment by HaloGenius** [comment]
Will be fixed in 0.6-204
