### ISSUE TITLE
GPU driver error no temps

### ISSUE THREAD

**Issue by fishcakedev** [minershive/hiveos-linux#109]
Hi,

in light of this forum thread [https://forum.hiveos.farm/t/3080-gpu-driver-error-no-temps/29827](https://forum.hiveos.farm/t/3080-gpu-driver-error-no-temps/29827)

There seems to be an unresolvable problem right now where the GPU would randomly throw a GPU driver error on mostly RTX 30 series cards.
Users already tried several things such as lowering OC, replacing thermal pads, etc. without success. 

From my own experience the error appears more frequently on latest nvidia driver but still very often on 455.45.01.
Hashrate Watchdog also seems to be unreliable as it doesn't always reboot HiveOS leading to several hours of idling away.

Any guidance on this issue?
Thank you!

**Comment by HaloGenius** [comment]
Please contact our technical support service with your question.
