### ISSUE TITLE
Hashrate Watchdog Algos mode 

### ISSUE THREAD

**Issue by shawnli87** [minershive/hiveos-linux#110]
When the Hashrate Watchdog mode is set to Algos, only the first miner using each algorithm is used to calculate the algorithm's current hashrate.

Example:
ethash minimum set to 300 mH/s
gminer (ethash) - 259.77 mH/s, teamredminer (ethash) - 56.86 mH/s, total ethash 316.63 mH/s
ethash low hashrate, rebooting

**Comment by shawnli87** [comment]
I think avg_khs is causing the problem. My syslog is filled with the following error:

`Apr  7 21:06:57 Testing_Rig avg_khs[19096]: jq: error (at <stdin>:1): number (261594) and string ("56870") cannot be added`
`Apr  7 21:06:57 Testing_Rig avg_khs[19096]: JSON parsing error`

**Comment by shawnli87** [comment]
> > When the Hashrate Watchdog mode is set to Algos, only the first miner using each algorithm is used to calculate the algorithm's current hashrate.
> > Yes, you are absolutely right. Only hashrate of first miner will be used by watchdog. We will add description into watchdog setup form soon.
> 
> > Yes, you are absolutely right. Only hashrate of first miner will be used by watchdog. We will add description into watchdog setup form soon.

So this is intentional? Wouldn't it make more sense to use the combined hashrate for each algorithm? Otherwise you would miss if the second+ miner(s) lose hashrate.

**Comment by HaloGenius** [comment]
> So this is intentional? Wouldn't it make more sense to use the combined hashrate for each algorithm? Otherwise you would miss if the second+ miner(s) lose hashrate.

As a rule, mix-rigs are not used on an industrial scale, therefore it is not in demand primarily from commercial clients.
In the future, it is possible that some solution will be implemented, but this task is not a high priority.
