### ISSUE TITLE
Title not matching total ethash when >1 miner

### ISSUE THREAD

**Issue by vlad88sv** [minershive/hiveos-linux#112]
![image](https://user-images.githubusercontent.com/91489/115823922-6ea29b80-a3c4-11eb-9095-bcc5a649cdd6.png)

**Comment by vlad88sv** [comment]
Also nothing in here
![image](https://user-images.githubusercontent.com/91489/115859752-d9b49800-a3ed-11eb-8b07-041396cf4a0d.png)

**Comment by HaloGenius** [comment]
Please see README to repository
