### ISSUE TITLE
 Does not show CPU Temp on AMD

### ISSUE THREAD

**Issue by ezshua** [minershive/hiveos-linux#115]
Hello

Motherboard
M2N4-SLI ASUSTeK Computer INC. (ASUS M2N4-SLI ACPI BIOS Revision 0301 07/14/2006)
CPU
2 × AMD Athlon(tm) 64 X2 Dual Core Processor 4400+
Disk Model
ATA WDC WD800JB-00JJ 80.0GB
System type
linux
Kernel
5.4.0-hiveos #108

0.6-204@210608
OS VERSION

CPU TEMP 0°

Temperature from CPU always zero degrees after update!
Temperarure from GPU show without problem!

sensors output:

k8temp-pci-00c3
Adapter: PCI adapter
Core0 Temp:   +34.0°C  
Core0 Temp:   +28.0°C  
Core1 Temp:   +37.0°C  
Core1 Temp:   +37.0°C  

atk0110-acpi-0
Adapter: ACPI interface
Vcore Voltage:      +1.28 V  (min =  +1.45 V, max =  +1.75 V)
 +3.3 Voltage:      +3.34 V  (min =  +3.00 V, max =  +3.60 V)
 +5.0 Voltage:      +4.95 V  (min =  +4.50 V, max =  +5.50 V)
+12.0 Voltage:     +11.97 V  (min = +11.20 V, max = +13.20 V)
CPU FAN Speed:     1366 RPM  (min =    0 RPM, max = 1800 RPM)
CHASSIS FAN Speed:    0 RPM  (min =    0 RPM, max = 1800 RPM)
POWER FAN Speed:      0 RPM  (min =    0 RPM, max = 1800 RPM)
CPU Temperature:    +38.0°C  (high = +90.0°C, crit = +125.0°C)
MB Temperature:     +34.0°C  (high = +70.0°C, crit = +125.0°C)

What I can do with it or how fix it?

**Comment by HaloGenius** [comment]
k8 platform it's too old and temp reporting not supported
