### ISSUE TITLE
Day is not shown in datetime string of next occurance of a scheduled event.

### ISSUE THREAD

**Issue by mike-brady** [minershive/hiveos-linux#118]
Here are two schedule tasks, each set to repeat daily. Seen in this screenshot, each task shows the occurrence of the next time it will run as `M Y HH:MM:SS`.
`Next at Jul 2021 23:00:12` and `Next at Jul 2021 18:00:00`.
The day is missing. Additionally, displaying the seconds appears to be unnecessary as you can only schedule tasks down to the minute and seconds are also not displayed in the above datetime string that represents the task's start datetime.

This should be displayed in the format `d, M Y HH:MM` to match the datetime string format of the start of the task.
`Next at 3rd, Jul 2021 23:00` and `Next at 3rd, Jul 2021 18:00`.

![Capture](https://user-images.githubusercontent.com/33209281/124355114-9476c880-dbdd-11eb-84d0-8f3a797463b0.PNG)

**Comment by HaloGenius** [comment]
As mentioned on [README](https://github.com/minershive/hiveos-linux/blob/master/README.md) development on GitHub stopped.
For bugs reports and new features request send it to support e-mail bee@hiveos.farm
Thank you for understanding.
