### ISSUE TITLE
hive-replace cannot get size

### ISSUE THREAD

**Issue by raulvasquez** [minershive/hiveos-linux#128]
Trying to run hive-replace on an Ubuntu install that is on nvme0n1p11. The script halts due to not detecting any value for the drives capacity. I need to dig a little more, but at first glance I think it is due to the partition number containing multiple digits for this scenario.

**Comment by raulvasquez** [comment]
Basically the error comes from this block. It is trimming -2 from the `nvme0n1p11` and  Ieaving `nvme0n1p` which size the space check.

```
	PART_UUID=`grep -oP "root=UUID=\K[^\s]+" /proc/cmdline` &&
		DISK_PART=`blkid -U "${PART_UUID}" | sed 's/\(^\/dev\/\)//'` ||
		DISK_PART=`grep -oP "root=/dev/\K[^\s]+" /proc/cmdline`

	[[ -z $DISK_PART ]] && echo -e "${RED}Unable to determine root disk${NOCOLOR}" && return 1

	if [[ "$(echo $DISK_PART | grep -c nvme)" -gt 0 ]]; then
		DISK_NAME=${DISK_PART::-2} #cutoff partnumber pN
	else
		DISK_NAME=${DISK_PART::-1} #cutoff partnumber N
	fi
```

I realize it is not common to see a disk with so many partitions. My scenario is a 3xmultiboot with win10  and manjaro for personal use, and an minimal ubuntu install I was hoping to hive-replace. Might make sense instead of trimming to count from the left:

```
	if [[ "$(echo $DISK_PART | grep -c nvme)" -gt 0 ]]; then
		DISK_NAME=${DISK_PART::7} #cutoff partnumber pN

```

**Comment by HaloGenius** [comment]
As mentioned on [README](https://github.com/minershive/hiveos-linux/blob/master/README.md) development on GitHub stopped.
For bugs reports and new features request send it to support e-mail bee@hiveos.farm
Thank you for understanding.
