### ISSUE TITLE
Please update `hive-opencl` package to v20.50

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [minershive/hiveos-linux#132]
As the title states - an update would be nice. Also please look into the legality of all the closed source stuff, its surprising how little code you guys have open-source, would not be surprised if there are multiple GPL violations.

Even if it's all legal - may I request to open source at least some of the stuff like package definitions? It totally makes sense to keep the core of HiveOS close source so competitors could not catch up/mimic it but having simple/low effort/low value stuff opensource would make life easier

**Comment by HaloGenius** [comment]
As mentioned on [README](https://github.com/minershive/hiveos-linux/blob/master/README.md) development on GitHub stopped.
For bugs reports and new features request send it to support e-mail bee@hiveos.farm
Thank you for understanding.
