### ISSUE TITLE
gpu-fans-find

### ISSUE THREAD

**Issue by vladimiryardan** [minershive/hiveos-linux#133]
Is there any arguments I can add to make the fans check spin longer?

ex.
gpu-fans-find -timeout=45

I see in line 12 of
https://github.com/minershive/hiveos-linux/blob/master/hive/bin/gpu-fans-find
`
# set timeout for fan test
timeout=15
`
can I change it to 60 and the fan spin test will be 60 seconds?

**Comment by HaloGenius** [comment]
As mentioned on [README](https://github.com/minershive/hiveos-linux/blob/master/README.md) development on GitHub stopped.
For bugs reports and new features request send it to support e-mail bee@hiveos.farm
Thank you for understanding.
