### ISSUE TITLE
HiveOS not detecting 4th GPU, major troubleshooting already done

### ISSUE THREAD

**Issue by plebosaur** [minershive/hiveos-linux#134]
System: ryzen 5 3400g, msi x470 motherboard, 2x rx570 1x rx470 1x 6600xt

No matter which one of my GPU's is placed in 4th, HiveOS will deny that it is detected. All of these GPUs are individually detected, and I have swapped out the risers for all of them confirming its not a riser related issue. 
I have reinstalled the rig on a flash of the stable and beta versions and even the upgraded pcie did not fix this for me. 
The 4th GPU will always spin up either before hiveOS starts or sometimes even during it. Sometimes Hive will make the fans spin on the 4th GPU but the system will recognize it as the 3rd one but the fans will spin on the 4th one. 
This is really bizarre, I am going to try more things before getting new components such as upgrading my motherboard bios. But other than that I am at a loss for what I can do to get my 4th GPU recognized. Please help me identify what is wrong with my system.

**Comment by HaloGenius** [comment]
As mentioned on [README](https://github.com/minershive/hiveos-linux/blob/master/README.md) development on GitHub stopped.
For bugs reports and new features request send it to support e-mail bee@hiveos.farm
Thank you for understanding.
