### ISSUE TITLE
[BUG] Bad path in "Hive Custom Miners" - /hive/miners/custom/custom

### ISSUE THREAD

**Issue by waltermelow** [minershive/hiveos-linux#137]
### Bad path in "Hive Custom Miners":

https://github.com/minershive/hiveos-linux/blob/72cae73d1f2788b999df30773091cad72e068de7/hive/miners/custom/custom#L60
Must be: `cd /hive/miners/$MINER_NAME/$CUSTOM_MINER`

https://github.com/minershive/hiveos-linux/blob/72cae73d1f2788b999df30773091cad72e068de7/hive/miners/custom/custom#L62
Must be: `[[ ! -e /hive/miners/$MINER_NAME/$CUSTOM_MINER/h-run.sh ]] &&`

https://github.com/minershive/hiveos-linux/blob/72cae73d1f2788b999df30773091cad72e068de7/hive/miners/custom/custom#L63
Must be: `echo -e "${RED}/hive/miners/$MINER_NAME/$CUSTOM_MINER/h-run.sh is not implemented${NOCOLOR}" && `

https://github.com/minershive/hiveos-linux/blob/72cae73d1f2788b999df30773091cad72e068de7/hive/miners/custom/custom#L68
Must be: `/hive/miners/$MINER_NAME/$CUSTOM_MINER/h-run.sh `

**Comment by sven-hash** [comment]
Got this error too

**Comment by sven-hash** [comment]
Here's the workaround I used

In the file `h-config.sh` at the end you can add (outside of the function)
```
MINER_NAME=miners/custom
miner_config_gen
```

**Comment by ATrump** [comment]
Hey guys!
Thanks for reporting this issue, but this script isn't used by actual HiveOS versions. If you have some difficulties with creating your custom miner integration, you can ask for a help in our foum (https://forum.hiveos.farm/c/miners/14).
Rgz!

**Comment by sven-hash** [comment]
Thanks for you answer, but this script is used or the documentation about how to create and integrate a custom is not up to date
