### ISSUE TITLE
[BUG] function miner_config_gen() never called

### ISSUE THREAD

**Issue by sven-hash** [minershive/hiveos-linux#138]
The miner_config_gen()  so the config is never generated

 https://github.com/minershive/hiveos-linux/blob/72cae73d1f2788b999df30773091cad72e068de7/hive/miners/custom/h-config.sh#L28

**Comment by ATrump** [comment]
Hey sven-hash!
Don't warry it's not a bug, this function is called from other HiveOS script. If your custom integration has some difficulties with creating config, you can ask for a help at our forum (https://forum.hiveos.farm/c/miners/14)
