### ISSUE TITLE
h-stats.sh: line 49: 0x0c value too great for base (error token is "0c")

### ISSUE THREAD

**Issue by chraac** [minershive/hiveos-linux#139]
https://github.com/minershive/hiveos-linux/blob/72cae73d1f2788b999df30773091cad72e068de7/hive/miners/teamredminer/h-stats.sh#L48

Recently I've experience following error after update to newest version of hiceos:
```log
./h-stats.sh: line 49: 0x0c
0c: value too great for base (error token is "0c")
```

After digging into the script, I found that there'are multi column in the variable ```bus_id``` like:
```
0c 0c 0c 0c
```

So maybe we should select the first column of the ```bus_id``` by awk before we translate it to decimal number:
```
bus_id=`echo ${bus_id} | awk '{print $1}'`
```

**Comment by chraac** [comment]
And attach the log file
[teamredminer_head.log](https://github.com/minershive/hiveos-linux/files/7778086/teamredminer_head.log)

**Comment by ATrump** [comment]
Hey chraak!
It looks like you are having network issues that caused TRM to restart multiple times and on every restart it would add the initial GPU lines to the log. That's why there were multiple values in bus_id.
I'll fix it soon. Thanks for the information.
