### ISSUE TITLE
HiveOS with soft shutdown to wait cool down GPUs temp

### ISSUE THREAD

**Issue by lucaslccs** [minershive/hiveos-linux#146]
We need a feature/option to "soft" shutdown the rig to **wait cool down the GPUs (core and memory) before turning off**, will be very appreciated for cards RTX3070Ti and above with high temps.

Suggested steps:
- miner stop
- shutdown -P 1min

Thanks in advance.

**Comment by lookfirst** [comment]
Why?

**Comment by heliosgnosis** [comment]
1 word fellow miner,   Delca  aka industraial computing case fans,  they will move 2000 square foot of hot air 25 feet across the room and out the window ,  maybe not so exact,  but heck 1 would make 5 gpus have zero hot air around them,  empties all air fully use 2 or 6 if you can handle the noise so freaking loud but the temps are impossible yet there they are no gpu over 50C max load

**Comment by lucaslccs** [comment]
> Why?

Mining dual coin the nvidia GPU is achieving about 65o on the core and 98o on the memory. The Hive shutdown can power off the rig in ~5seg and the GPU does not have sufficient time to cooldown the hardware. In frames with external fan they MAY continue flowing but in frame with fan supplied by same PSU, this is not true. This make sense? Thank you.
