### ISSUE TITLE
HiveOS freezes when loading multiple S7100X mxm cards

### ISSUE THREAD

**Issue by CYRiXplaysHalo** [minershive/hiveos-linux#148]
I have tried pretty much every version of HiveOS in the flash utility and the furthest I can get the OS to load with more than one S7100X mxm cards is where it freezes on loading the AMD drivers on the latest stable version ```hiveos-0.6-212-stable@211201```.

In terms of troubleshooting HiveOS works totally fine with only ONE card, but can not work with 2, 3, or 4 cards. I am using a BTC-T37 motherboard, with an 8GB SODIMM and ample power. To verify it wasn't bad cards or bad mxm to pcie adapters I have verify HiveOS will boot with each of the four cards I have when I only plug in one of them at a time. To HiveOS's credit I have tried minerstat's OS, NiceHash's OS, and simplemining's OS and none of them properly recognize the card to the point an OpenCL application can be loaded on them.

S7100X cards in HiveOS are detected as FirePro S7150's, also. 

To be clear the live it freezes at is:

```> Loading AMD drivers, 4 GPU```

**Comment by HaloGenius** [comment]
Please contact support to resolve this request.
