### ISSUE TITLE
Website and everything realated to HiveOS is slow

### ISSUE THREAD

**Issue by Druxlolz** [minershive/hiveos-linux#149]
Your client is bugged and has consistently timeouts from client to server with uptime information and such but who care anyways lol hiveOS is dog****

**Comment by HaloGenius** [comment]
Issues you mentioned do not apply to the Hive Os client and as mentioned in the [README.MD](https://github.com/minershive/hiveos-linux/blob/master/README.md) file are not discussed here.
If you have questions/issues/suggestions, please contact technical support on [Hiveon](https://hiveon.com) website.
