### ISSUE TITLE
Unrecognized card when using 3xNavi21 and B85 

### ISSUE THREAD

**Issue by chraac** [minershive/hiveos-linux#150]
Recently I've tried but a rig with 3* navi21 card on an old B85 platform, and I found that with 2 cards it works well, but when I install 3 cards. the first cards was unrecognized by the hiveos, following is the output of lspci:
```log
04:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Navi 21 [Radeon RX 6800/6800 XT / 6900 XT] (rev c3) (prog-if 00 [VGA controller])
	Subsystem: ASUS Device 04f6
	Control: I/O+ Mem- BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr+ Stepping- SERR+ FastB2B- DisINTx-
	Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
	Interrupt: pin A routed to IRQ 18
	Region 0: Memory at d0000000 (64-bit, prefetchable) [disabled] [size=256M]
	Region 2: Memory at <ignored> (64-bit, prefetchable) [disabled]
	Region 4: I/O ports at 5000 [size=256]
	Region 5: Memory at 78000000 (32-bit, non-prefetchable) [disabled] [size=1M]
```

Looks there's no address assigned to the `Region 2` which cause the problem, so I run `dmesg`, and found that:
```
[   22.430921] amdgpu 0000:04:00.0: BAR 0: assigned [mem 0xd0000000-0xdfffffff 64bit pref]
[   22.430933] amdgpu 0000:04:00.0: BAR 2: no space for [mem size 0x00200000 64bit pref]
[   22.430934] amdgpu 0000:04:00.0: BAR 2: failed to assign [mem size 0x00200000 64bit pref]
[   22.431061] [drm:amdgpu_device_init [amdgpu]] *ERROR* sw_init of IP block <gmc_v10_0> failed -19
```
The system can't allocate space for the PCIe BAR 2 of device `0000:04:00` which is the unrecognized GPU.

After googling, I've found that the PCIe BAR address problem is mainly cause by an ill-implemented BIOS of MB vendor, so we can append a kernel boot parameter ( `pci=nocrs` ) into grub boot menu, to ignore the BIOS allocated address and let the kernel configure it automatically.

So I just wandering if we can add a switch inside our dashboard to let the user enable the `pci=nocrs` boot parameter for some older model MB?

**Comment by chraac** [comment]
[rig_unrecognize_card.zip](https://github.com/minershive/hiveos-linux/files/8694479/rig_unrecognize_card.zip)
Here's the full log of dmesg and lspci before and after applying the boot parameter `pci=nocrs`.

**Comment by HaloGenius** [comment]
you can use /hive/etc/grub.custom file
add `pci=nocrs` to this file, run `selfupgrade -g` and reboot rig

**Comment by chraac** [comment]
Thanks, works well on my rig
