### ISSUE TITLE
[BUG] BIOS flash fails AMDVBFLASH v 4.100 error 0FL01 

### ISSUE THREAD

**Issue by andi-christ** [minershive/hiveos-linux#151]
Flashing BIOS onto AMD RX5700[XT] cards through web management portal (the.hiveos.farm) fails giving error:

The result of RSA signature verify is FAILED.
BIOS authentication signature mismatched

   ERROR: 0FL01
   
- "Force flashing ignoring security checking" has no effect
- BIOS being used is known to be good - has been used on 10+ other identical cards for over 12 months
- The edits to the new bios over the old are alterations to the memory strap timings
- Flashing is successful if the BIOS used is identical to that already present in the card
- it appears that HiveOS AMVBFLASH version has been upgraded recently
![image](https://user-images.githubusercontent.com/12095704/177890941-adff6f67-72e7-4bdb-a43e-915f47aa9712.png)

**Comment by eugenedev0** [comment]
Have the same issue with latest hiveOS version 0.6-218
hiveos-0.6-203-stable works well.

**Comment by HaloGenius** [comment]
Original version of amdvbflasher v4.100 not supporting disabling/ignoring VBIOS check
v4.100+ it's patched version that comes with latest Hive OS Linux client v0.6-219 should fix it
