### ISSUE TITLE
3060ti 

### ISSUE THREAD

**Issue by viponedream** [minershive/hiveos-linux#152]
SET POWER LIMIT: 150.0 W [Unknown Error]
(exitcode=123)
  SET GPU CLOCKS: 950 MHz
  Max Perf mode: 4 (auto)
  Attribute 'GPUGraphicsClockOffset' was already set to 0
ERROR: Error assigning value 1400 to attribute
       'GPUMemoryTransferRateOffset' (CAT-1-1:0[gpu:3]) as specified in
       assignment '[gpu:3]/GPUMemoryTransferRateOffset[4]=1400' (Unknown
       Error).
(exitcode=100)

**Comment by HaloGenius** [comment]
Contact customer support with your problem
