### ISSUE TITLE
If current temp > target temp and speed = max speed, decrease power to lower temps.

### ISSUE THREAD

**Issue by overcookedpanda** [minershive/hiveos-linux#28]
In nvOC and forks, the auto fan/temp control script will lower the PL of the card to ensure the target temp is accomplished if the fans are at their max setting and the temperate remains above, I believe this is a very useful feature and was wondering if it could be implemented into the autofan script.  I believe in the standalone version it already exists per Steambot

**Comment by minershive** [comment]
Yes, but in Hive we don't consider it useful. 
E.g. you have PL 80 and the minimum is 75. GPU is unstable at minimal PL.
If your card is not capable of preserving the target temp you should do something with your cooling and overclocking.

**Comment by overcookedpanda** [comment]
In the script logic, you simply specify that the PL should not be lower than the min PL of the GPU.

I do understand what you are saying but I feel you are thinking of it wrong.  In my instance the problem occurs not due to bad cooling per se, but extremely hot days (hotter than normal), and if I decrease my PL by 5 watts, it is able to stay within the normal range.

**Comment by calebcall** [comment]
It would be very helpful to be able to specify min and max temps that your cards can run at and be stable and then hive could work within that range.  I would love to be able to add more cooling for my rigs but I'm not able to. Same as panda, I can lower my PL a small amount and my temps follow as well.

**Comment by minershive** [comment]
Right now now it's possible use autofan.conf manually to set target temp
