### ISSUE TITLE
Disable P2 mode for CUDA (prevent instability)

### ISSUE THREAD

**Issue by DaniloJacques** [minershive/hiveos-linux#41]
Hi!

I was looking for a fix to "Force P2 state for CUDA" as we have in Windows (through nVidia Inspector). After some searches, googles, hair loss, I found it: https://github.com/ethereum-mining/ethminer/issues/456#issuecomment-370224878

P2 is the cause of many instabilities. I think the fix could be tested.

There is three procedures explained in the link provided:
1- Disable P2 by setting P1 as default.
`nvidia-settings -a [gpu:0]/GPUPowerMizerMode=1`

2- Set Compute Mode to NVIdia cards (I don't have sure that it helps)
`nvidia-smi --gom=COMPUTE`

3- Set PERFORMANCE clocks (I think it prevents clock fluctuation)
`nvidia-smi -q -d PERFORMANCE`

Could you take a look at this? I think if it's correct we could improve stability and performance.

Thank you!

**Comment by minershive** [comment]
It's easy to test.
Edit `/home/user/xinit.user.sh`, put there:
nvidia-smi --gom=COMPUTE
nvidia-smi -q -d PERFORMANCE

Though it didn't have effect on my P106
```
root@worker:~# nvidia-smi --gom=COMPUTE
GOM mode cannot be changed on GPU 00000000:01:00.0.
Treating as warning and moving on.
All done.
Press any key to continue...

root@worker:~# nvidia-smi -q -d PERFORMANCE

==============NVSMI LOG==============

Timestamp                           : Mon Jul 23 23:09:27 2018
Driver Version                      : 390.59

Attached GPUs                       : 1
GPU 00000000:01:00.0
    Performance State               : P0
    Clocks Throttle Reasons
        Idle                        : Not Active
        Applications Clocks Setting : Not Active
        SW Power Cap                : Active
        HW Slowdown                 : Not Active
            HW Thermal Slowdown     : Not Active
            HW Power Brake Slowdown : Not Active
        Sync Boost                  : Not Active
        SW Thermal Slowdown         : Not Active
        Display Clock Setting       : Not Active
```

**Comment by DaniloJacques** [comment]
Okay! Thanks! Compute mode apparently works only with Maxwell cards.

What about item 1? It's the more important for me. :)

If it works, we can improve stability. I'm having good results in Windows with it (by disabling p2)

**Comment by DaniloJacques** [comment]
Thanks. Closing now.
