### ISSUE TITLE
Agent stop working

### ISSUE THREAD

**Issue by biospb** [minershive/hiveos-linux#46]
Sometimes agent stop working after reboot (it hangs in gpu-stats script on getting data from pwm1 or temp_input1 of some AMD cards). It looks like this
![agent_bug](https://user-images.githubusercontent.com/42325079/44006047-fa8165d8-9e85-11e8-836e-8a6f35b5f948.jpg)

Run gpu-stats with timeout function does not solve this problem. Watchdogs does not help also. HW watchdog works and does not reboot rig. Hashrate watchdog does not work as miner does not start. 

I can suggest 3 ways to fix this and other similar problems.

1. Ping HW watchdog from agent. (Does not help if there is no watchdog)

2. Check from cron if agent is working. For example, if last update time is more than 1 minute - restart agent. If more than 3 minutes - reboot rig. (Agent must update something before sleeping)

3. Run gpu-stats in separate screen. It can also help with situation when nvidia-smi needs more time to get statistics (up to 10 seconds per gpu with high load average). At this moment if nvidia-smi does not get data in 10 seconds - there will no temps & fans 
![highload](https://user-images.githubusercontent.com/42325079/44006221-37c4fcf4-9e89-11e8-83a6-0632305cfd45.jpg)

**Comment by minershive** [comment]
On your screens the agent is working. If it would not work the rig would become offline.

There is solution with autofan script, were you can set reboot on temp errors.

**Comment by biospb** [comment]
Rig becomes offline. It send few times and stop. Time on screen is 21:54, and latest response was 08:12.

Second screen is from another rig with another problem. I can make separate issue for this.
btw, auto fan will not help - rig will reboot every few minutes (after LA get more than 8.0 after 2 minutes or so...) nvidia-smi response in about 2 minutes. but agent wants in 10 seconds

**Comment by minershive** [comment]
Please run `ps aux` when agent is hanging, let's see what process is waiting.
Is it with amd or nvidia cards?

**Comment by biospb** [comment]
it is waiting in gpu-stats on reading from hwmon..... pwm1 from one card (AMD). 
exactly here - [[ -e ${hwmondir}pwm1 ]] && fan=`head -1 ${hwmondir}pwm1` || fan=0   
but if comment this line it hangs on - temp=`head -1 ${hwmondir}temp1_input`
only on one card. 
probably it can happen with any other param.
using timeout -s9 5s with head... or gpu-stats itself - does not help. it hangs on buggy card.
only rig reboot helps.

**Comment by minershive** [comment]
Ok,  I will consider improving this. Thank you.

**Comment by biospb** [comment]
Thanks in advance.

**Comment by minershive** [comment]
From 0.5-72 gpu-stats is runing in another thread.
