### ISSUE TITLE
sometimes miner does not restart (claymore and lot of gpus)

### ISSUE THREAD

**Issue by biospb** [minershive/hiveos-linux#48]
Miner does not restart after wallet change or restart command when using Claymore and 13x GPU. 13x NVIDIA - Always. 13x AMD - sometimes.
Stop miner, then restart - works! Restart miner, one more restart - works. Apply new wallet (or change settings in wallet) - does not work. Need restart after. Seems happen only with claymore. But it is possible with others.

There is "claymore is already running" in miner log after restart. So it seems that during restart screen is closed but claymore is not. And then it does not start as it is still running.
![restart-bug1](https://user-images.githubusercontent.com/42325079/44022332-f8bb0302-9eef-11e8-8c9f-63e2f071eeeb.jpg)
![restart-bug2](https://user-images.githubusercontent.com/42325079/44022333-f8d7df40-9eef-11e8-9bfd-8508e03c93fa.jpg)

Some checks need to be added to be sure miner is closed.

**Comment by minershive** [comment]
Are you still having this issue?

**Comment by biospb** [comment]
yes, tested on 0.5-73

Restarting miner
Stopping screen session 26521
Starting claymore, cpuminer-opt

in miner log - claymore miner is already running

**Comment by minershive** [comment]
Write in Telegram to @dimafern please

**Comment by minershive** [comment]
Fixed here
https://github.com/minershive/hiveos-linux/commit/0e3e5e5ef0a2aa743b79a5fac45b43f539587c17
