### ISSUE TITLE
Monero Algo OC

### ISSUE THREAD

**Issue by ernest22** [minershive/hiveos-linux#51]
<img width="1220" alt="screen shot 2018-08-24 at 12 47 11 pm" src="https://user-images.githubusercontent.com/19405522/44565665-e7787200-a79b-11e8-896e-957657026aad.png">

I am mining monero but when I check the overclock setting on Hive 2, it is using the cryptonight profile but nit the v7 profile.

**Comment by HaloGenius** [comment]
We know about this issue.
OC settings the same for all cryptonight variants.

**Comment by ernest22** [comment]
Looks like it is fixed thanks
