### ISSUE TITLE
w83627ehf module

### ISSUE THREAD

**Issue by kkkrackpot** [minershive/hiveos-linux#53]
Hi,

Is it possible to add `w83627ehf` module for hardware monitoring chip?

**Comment by kkkrackpot** [comment]
Actually, I don't know what exactly is needed to add this module into HiveOS image... On a working installation I couldn't find it with `modinfo`, so I decided it's missing in the distro.

AFAIK it's an in-kernel module since long ago https://www.kernel.org/doc/Documentation/hwmon/w83627ehf

**Comment by minershive** [comment]
Try this
root@worker:~# modprobe w83627ehf
modprobe: ERROR: could not insert 'w83627ehf': No such device

But i get an error as i don't have this device

**Comment by minershive** [comment]
```
root@worker:~# modinfo w83627ehf
filename:       /lib/modules/4.13.16-hiveos/kernel/drivers/hwmon/w83627ehf.ko
license:        GPL
description:    W83627EHF driver
author:         Jean Delvare <jdelvare@suse.de>
srcversion:     46E4FAEA421C7A55FD16E18
depends:        hwmon-vid
intree:         Y
name:           w83627ehf
vermagic:       4.13.16-hiveos SMP mod_unload 
parm:           force_id:Override the detected device ID (ushort)
parm:           fan_debounce:Enable debouncing for fan RPM signal (ushort)
```

**Comment by kkkrackpot** [comment]
It's working now, thanks!
