### ISSUE TITLE
ATIFLASH support for 10+ GPUs

### ISSUE THREAD

**Issue by biospb** [minershive/hiveos-linux#58]
Current version of ATIFLASH does not work with more than 10 GPUs.
Here is fixed version:
[atiflashfixed.zip](https://github.com/minershive/hiveos-linux/files/2456101/atiflashfixed.zip)
Atiflash v4.25.1 patched by me
commands -p -s -i -ai now work with 16 GPUs using A B C D E F for 10+ GPU.

![atiflash-info](https://user-images.githubusercontent.com/42325079/46611484-a2738980-cb16-11e8-840f-1b2380505ccc.png)
![atiflash-prog](https://user-images.githubusercontent.com/42325079/46611485-a2738980-cb16-11e8-8d0a-35cfe4a7fa4c.png)

**Comment by minershive** [comment]
Commited. Will be in next update.

**Comment by MoneroCrusher** [comment]
@biospb is it possible to implement polaris12 / RX 550 flash support?
