### ISSUE TITLE
Update delay bug

### ISSUE THREAD

**Issue by Simaex** [minershive/hiveos-linux#60]
I am experiencing update bug with last few HIVE versions. Few days after Telegram notification I am unable to update. The update button is highglighted but after depressing it shows "you have the latest version" and do nothing. In two to five days the rig updates without any changes from my side. It is a bit annoying just before today's Monero fork.
Please look into it.

**Comment by minershive** [comment]
for support write to bee@hiveos.farm
when you click to update you get a message back with the log, please look into it for details
