### ISSUE TITLE
Feature Suggestion: AutoOC

### ISSUE THREAD

**Issue by ryanmarfone** [minershive/hiveos-linux#66]
Would love a feature that suggests OC profiles for the detected cards and algorithm. That would be amazing, especially for workers that have mixed cards. Could be a huge value proposition for paid accounts. MVP could be based off of what the majority of other HiveOS users are doing (use at your own discretion, etc).

**Comment by minershive** [comment]
Yes, this will be available soon

**Comment by ezephillips** [comment]
Maybe Apply OC based on Status of the gpus? HR,InvalidsShares,temp? Like AutoTune for ASICS? This whoud be the glory!!! 💯
