### ISSUE TITLE
hive-help (enhancement)

### ISSUE THREAD

**Issue by MaynardMiner** [minershive/hiveos-linux#67]
Maybe there is one that I don't know about, but I propose a hive-help bash script being made for users to see all hive terminal commands, and what they do. It may be cool to add basic and extremely useful linux commands as well for total newbies to linux.

I personally am having to constantly pass users forum posts of hive command lists. It seems it would just be easier to tell them to type ``hive-help``. I may be writing this not knowing there is one already...if there is...I can't find it.

There are a lot of commands at this point. Even I can't remember them all. Haha- Not complaining.

**Comment by salvo2002** [comment]
not all inclusive but there is 'helpme'
https://github.com/minershive/hiveos-linux/blob/master/hive/bin/helpme

**Comment by minershive** [comment]
I try to keep `helpme` small enough to fit on screen. It's proposed to edit commands list on forum. Will update this topic.
https://forum.hiveos.farm/t/useful-linux-commands-for-beginners/3337

**Comment by MaynardMiner** [comment]
I didn't know about ``helpme``. I have been directing users to it now as I answer questions on HiveOS discord as well as my own.

I understand wanting it to fit on screen.

Closing.
