### ISSUE TITLE
Git commits

### ISSUE THREAD

**Issue by VaiYav** [minershive/hiveos-linux#69]
Здравствуйте, господа! Мне нравится ваша ОС, но мне не нравится то как вы ведете историю коммитов. Пролистав страницы я увидел коммиты с одинаковым названием, которые дублируются 2, а иногда даже 3 раза, ну это такая придирка конечно, это **ВАШ** проект и **ВАМ** решать как использовать функционал гита, но я бы на вашем месте сквошил такие коммиты (git rebase -i HEAD~n), ну и возможно добавлял бы к названию коммита префикс что было реализовано ([Fix], [Feature], [Release]), я думаю вам стало бы проще ориентироваться. Успехов в разработке!

P.S. Ну а вообще гитхаб не очень удобный как по мне в разработке, мне больше нравится gitlab, а то я даже хз как лейбл повесить)

**Comment by HaloGenius** [comment]
As you said naming of commits its internal matter of each team
Any way thank you for suggestion
