### ISSUE TITLE
hello fails when interface has more than one ip address

### ISSUE THREAD

**Issue by git-moiseev** [minershive/hiveos-linux#70]
Fix
/hive/bin/hello
@@ -56,7 +56,7 @@
-lan_address=`ip -o -f inet addr show | grep eth0 | awk '/scope global/ {print $4}'`
+lan_address=`ip -o -f inet addr show | grep eth0 | awk 'BEGIN {ORS=" "} /scope global/ {print $4}'`

**Comment by HaloGenius** [comment]
fixed
