### ISSUE TITLE
bminer doesn't reports hashrate

### ISSUE THREAD

**Issue by pawelantczak** [minershive/hiveos-linux#86]
Hello.
When using bminer, hashrate is not shown next to each GPU and it's not reported via API.
![image](https://user-images.githubusercontent.com/171534/60076317-8e64cc00-9727-11e9-8284-1407b15579bc.png)

**Comment by HaloGenius** [comment]
What is the problem? In this screenshot, everything is displayed ... Can you show on another example or describe in more detail?

**Comment by HaloGenius** [comment]
Ohhh ....its a very old old song
Hashrate values displayed in this area for miners which reported also bus id for card in addition to gpu id from miner. With this values we can definitely associate hashrate from GPUx with their bus_id. It's very important when 2+ miners running on the same rig and prevents visual artefacts

**Comment by pawelantczak** [comment]
Understood.
