### ISSUE TITLE
what's the hardware requirement?

### ISSUE THREAD

**Issue by yucejun** [minershive/hiveos-linux#89]
What's the hardware requirement? Need GPU with 4GB VRam? Can CPU or low end CPU(mybe 1GB VRam) mining?

**Comment by HaloGenius** [comment]
It's depends which coin you planned to mine.
Hive OS Linux client supports GPU mining as basic function and CPU mining as additional also is possible (miners are included for this).
For GPU mining we recommended 4G RAM for system and 4G VRAM for video cards.
CPU power and model for GPU mining depends how actively the processor is used by the miner. For example, when mining on the ethash algorithm, the processor is practically not involved. On other algorithms, the processor can be significantly involved in the calculations or validation of the received data.
Other hardware requirements strictly depends from what you want to mine. Hive can boot with 1G RAM and iGPU onboard.
