### ISSUE TITLE
Special characters may break wifi setup

### ISSUE THREAD

**Issue by thundo** [minershive/hiveos-linux#90]
If you have a special character in your wifi password the wifi config generation script may break because of sed use of special characters.

For instance, if you have a wifi password like `FOO&BAR` the substitution script at https://github.com/minershive/hiveos-linux/blob/master/hive/sbin/wifi#L131

will generate a bad `wifi.txt`.

> WIFI_SSID="..."
> 
> WIFI_PASSWORD="FOOWIFI_PASSWORD=""BAR"

(template: https://github.com/minershive/hiveos-linux/blob/master/hive/etc/hive-config.stub/network/wifi.txt)

The same may apply to the WIFI_SSID substitution.

Thank you

**Comment by biospb** [comment]
Yes. it is broken with a lot of symbols.
I will fix it in upcoming release
Thanks for reporting
