### ISSUE TITLE
CPU mining - multiple threads visual glitch

### ISSUE THREAD

**Issue by pawelantczak** [minershive/hiveos-linux#91]
Hi.
Since RandomX is coming I'm preparing my setup.
With multiple threads, much more than possible GPUs attached, there is a visual glitch in dashboard.
![image](https://user-images.githubusercontent.com/171534/69261598-23c69800-0bc2-11ea-834e-7f2b9f82c201.png)

**Comment by HaloGenius** [comment]
Hello!
On further Monero’s hardfork, we paid attention to this and it’s already in the list of tasks to be fixed
Thank you for using Hive OS

**Comment by pawelantczak** [comment]
Thanks.

**Comment by HaloGenius** [comment]
Can you contact with us. I'm also see zero temp and want to fix it
