### ISSUE TITLE
Huge pages size for RandomX

### ISSUE THREAD

**Issue by pawelantczak** [minershive/hiveos-linux#92]
Hi.
Currently vm.nr_hugepages is set to 128.
For RandomX it needs to be much bigger, something around 2400.
I have two Xeon with 4 channel memory.

**Comment by HaloGenius** [comment]
Hello!
We will consider how to do it better, because not all configurations will fit such a large vlaue and this is mainly necessary only for RandomX.

**Comment by HaloGenius** [comment]
`hugepages` tool
