### ISSUE TITLE
Question on watchdog rebooting

### ISSUE THREAD

**Issue by zethereumGmail** [minershive/hiveos-linux#98]
When a GPU starts flaking out, the watchdog service running on HiveOS seems to want to reboot the entire system. Isn't there something else that can be done; perhaps disable the problem GPU and re-enable it?

Here is an example:

WATCHDOG: GPU 0 hangs in OpenCL call, exit
WATCHDOG: GPU 0 hangs in OpenCL call, exit
Rebooting
> Sending with payload "danger": Claymore Reboot: WATCHDOG: GPU 0 hangs in OpenCL call, exit
{"method":"message","jsonrpc":"2.0","id":0,"params":{"rig_id":"xxxxxx","passwd":"**********","type":"danger","data":"Claymore Reboot: WATCHDOG: GPU 0 hangs in OpenCL call, exit\r","payload":"[3305 bytes]"}}

Thanks

**Comment by HaloGenius** [comment]
It's not linux releated
